# Generated by Django 3.2.5 on 2021-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categtable',
            fields=[
                ('ctname', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
