# Generated by Django 3.2.5 on 2021-12-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_wishlisttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('wshlist_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='wishlisttable',
        ),
    ]
