# Generated by Django 3.2.5 on 2021-11-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartlist',
            fields=[
                ('cart_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
