# Generated by Django 3.2.5 on 2021-11-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
